name: Execute PowerShell Script

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-powershell-script:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Execute PowerShell Script
        run: |
          pwsh ./path/to/your/script.ps1