name: Run PowerShell and Upload to Gist

on:
  push:
    branches:
      - main  # or any branch you prefer
  workflow_dispatch:

jobs:
  generate-and-upload:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run PowerShell script
      run: |
        ./scripts/merge.ps1  # adjust the path and script name as needed

    - name: Upload JSON to Gist
      run: |
        $filePath = "./generated_data/jsonresume.json"  # adjust path if necessary
        $gistId = "40eece97259fe4f9eb8936ac089d34b9"
        $token = "${{ secrets.GIST_TOKEN }}"
        $content = Get-Content $filePath -Raw
        $payload = @{
          "files" = @{
            "jsonresume.json" = @{
              "content" = $content
            }
          }
        } | ConvertTo-Json -Depth 10

        Invoke-RestMethod -Uri "https://api.github.com/gists/$gistId" `
                          -Method PATCH `
                          -Body $payload `
                          -Headers @{ Authorization = "token $token" }
      shell: pwsh