name: Execute PowerShell Script

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-powershell-script:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Execute PowerShell Script
        run: |
          pwsh ./scripts/merge.ps1

      - name: Confirm Script Execution
        run: echo "PowerShell script execution completed successfully!"

      - name: Set up Git credentials
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create new branch and commit changes
        run: |
          git checkout -b update-jsonresume-${{ github.run_id }}
          git add ./generated_data/jsonresume.json
          git commit -m "Update generated jsonresume.json"
          git push origin update-jsonresume-${{ github.run_id }}