name: Run PowerShell and Upload to Gist

on:
  push:
    branches:
      - main  # or any branch you prefer
  workflow_dispatch:

jobs:
  generate-and-upload:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Upload NO JSON to Gist
      run: |
        $filePath = "./publish/no/jsonresume.json"  # adjust path if necessary
        $gistId = "f8b84db7b56f189c4cd5ae57cfc88df5"
        $token = "${{ secrets.GIST_TOKEN }}"
        $content = Get-Content $filePath -Raw
        $payload = @{
          "files" = @{
            "jsonresume.json" = @{
              "content" = $content
            }
          }
        } | ConvertTo-Json -Depth 10

        Invoke-RestMethod -Uri "https://api.github.com/gists/$gistId" `
                          -Method PATCH `
                          -Body $payload `
                          -Headers @{ Authorization = "token $token" }
      shell: pwsh

    - name: Upload EN JSON to Gist
      run: |
        $filePath = "./publish/en/jsonresume.json"  # adjust path if necessary
        $gistId = "a241fb28e24fc7674d804f63fc2cfcf0"
        $token = "${{ secrets.GIST_TOKEN }}"
        $content = Get-Content $filePath -Raw
        $payload = @{
          "files" = @{
            "jsonresume.json" = @{
              "content" = $content
            }
          }
        } | ConvertTo-Json -Depth 10

        Invoke-RestMethod -Uri "https://api.github.com/gists/$gistId" `
                          -Method PATCH `
                          -Body $payload `
                          -Headers @{ Authorization = "token $token" }
      shell: pwsh