name: Execute PowerShell Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  run-powershell-script:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Execute PowerShell Script
        run: |
          pwsh ./scripts/merge.ps1

      - name: Confirm Script Execution
        run: echo "PowerShell script execution completed successfully!"

      - name: Set up Git credentials
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes (for PR)
        run: |
          git checkout -b update-jsonresume-${{ github.run_id }}
          git add ./generated_data/jsonresume.json
          git commit -m "Update generated jsonresume.json"

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update generated jsonresume.json"
          branch: update-jsonresume-${{ github.run_id }}
          title: "Update jsonresume.json"
          body: "This PR was auto-generated by the workflow."

      - name: Enable Auto-Merge
        if: steps.cpr.outputs.pull-request-number != ''
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash