name: Execute PowerShell Script

on:
   workflow_dispatch

permissions:
  contents: write
  pull-requests: write

jobs:
  run-powershell-script:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Execute PowerShell Script
        run: pwsh ./scripts/merge.ps1

      - name: Confirm Script Execution
        run: echo "PowerShell script execution completed successfully!"

      - name: Check for file changes
        id: diff
        shell: bash
        run: |
          if git diff --quiet && git diff --cached --quiet; then
            echo "No changes detected"
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected"
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        id: cpr
        if: steps.diff.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update generated jsonresume.json"
          add-paths: |
            generated_data/jsonresume.json
          branch: update-jsonresume-${{ github.run_id }}
          title: "Update jsonresume.json"
          body: "This PR was automatically created by the workflow."
          base: main
          delete-branch: true

      - name: Enable Auto-Merge
        if: steps.cpr.outputs.pull-request-number != ''
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash